// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Cpp_calc_minfo
NumericVector Cpp_calc_minfo(arma::mat prob_mat, arma::vec wt_vec, int normalized);
RcppExport SEXP _hidgenclassifier_Cpp_calc_minfo(SEXP prob_matSEXP, SEXP wt_vecSEXP, SEXP normalizedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type prob_mat(prob_matSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wt_vec(wt_vecSEXP);
    Rcpp::traits::input_parameter< int >::type normalized(normalizedSEXP);
    rcpp_result_gen = Rcpp::wrap(Cpp_calc_minfo(prob_mat, wt_vec, normalized));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hidgenclassifier_Cpp_calc_minfo", (DL_FUNC) &_hidgenclassifier_Cpp_calc_minfo, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_hidgenclassifier(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
